apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "secret-sync-operator.fullname" . }}
  labels:
    {{- include "secret-sync-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets", "namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["sync.92ac.cn"]
  resources: ["secretsyncs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["sync.92ac.cn"]
  resources: ["secretsyncs/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["sync.92ac.cn"]
  resources: ["secretsyncs/finalizers"]
  verbs: ["update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "secret-sync-operator.fullname" . }}
  labels:
    {{- include "secret-sync-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "secret-sync-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "secret-sync-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}