---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sync.92ac.cn
  resources:
  - secretsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sync.92ac.cn
  resources:
  - secretsyncs/finalizers
  verbs:
  - update
- apiGroups:
  - sync.92ac.cn
  resources:
  - secretsyncs/status
  verbs:
  - get
  - patch
  - update
