# permissions for end users to view secretsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: secret-syncer
    app.kubernetes.io/managed-by: kustomize
  name: secretsync-viewer-role
rules:
- apiGroups:
  - sync.92ac.cn
  resources:
  - secretsyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sync.92ac.cn
  resources:
  - secretsyncs/status
  verbs:
  - get
