apiVersion: sync.92ac.cn/v1
kind: SecretSync
metadata:
  labels:
    app.kubernetes.io/name: secret-syncer
    app.kubernetes.io/managed-by: kustomize
  name: secretsync-sample
spec:
  secret_name: "qcloudregistrykey"
  namespaces: "default"
