name: Docker Image CI

on:
  push:
    tags:
      - 'v*'  # 匹配以 'v' 开头的 tag，例如 v1.0.0
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Extract tag name
      id: extract_tag
      run: |
        TAG_NAME=$(echo $GITHUB_REF | cut -d'/' -f3)
        echo "Extracted tag name: $TAG_NAME"
        echo "::set-output name=tag_name::$TAG_NAME"

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag deepwzh/secret-sync-operator:${{ steps.extract_tag.outputs.tag_name }}

    - name: Log in to Docker Hub
      if: github.event_name == 'push'
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Push the Docker image
      if: github.event_name == 'push'
      run: |
        docker push deepwzh/secret-sync-operator:${{ steps.extract_tag.outputs.tag_name }}
